IF NOT EXIST ".\Files" MKDIR ".\Files"
IF NOT EXIST ".\Files\x86" MKDIR ".\Files\x86"
IF NOT EXIST ".\Files\x64" MKDIR ".\Files\x64"
DEL /Q ".\Files\x86\*"
DEL /Q ".\Files\x64\*"
COPY /Y "..\StatsDownload.FileDownload.Console\bin\Release\netcoreapp2.0\publish-x86\*" ".\Files\x86"
COPY /Y "..\StatsDownload.StatsUpload.Console\bin\Release\netcoreapp2.0\publish-x86\*" ".\Files\x86"
COPY /Y "..\StatsDownload.FileDownload.Console\bin\Release\netcoreapp2.0\publish-x64\*" ".\Files\x64"
COPY /Y "..\StatsDownload.StatsUpload.Console\bin\Release\netcoreapp2.0\publish-x64\*" ".\Files\x64"
DEL /Q ".\Files\x86\*.pdb"
DEL /Q ".\Files\x86\*.xml"
DEL /Q ".\Files\x64\*.pdb"
DEL /Q ".\Files\x64\*.xml"
"c:\Program Files (x86)\WiX Toolset v3.11\bin\heat.exe" dir ".\Files\x86" -dr INSTALLFOLDER -gg -sfrag -sreg -scom -cg FilesGroup -var var.FileSource -out Files-x86.wxs
"c:\Program Files (x86)\WiX Toolset v3.11\bin\heat.exe" dir ".\Files\x64" -dr INSTALLFOLDER -gg -sfrag -sreg -scom -cg FilesGroup -var var.FileSource -out Files-x64.wxs