USE [master]
GO
/****** Object:  Database [FoldingCash]    Script Date: 6/29/2019 4:00:40 PM ******/
CREATE DATABASE [FoldingCash]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoldingCash', FILENAME = N'F:\Databases\FoldingCash\FoldingCash.mdf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'FoldingCash_log', FILENAME = N'F:\Databases\FoldingCash\FoldingCash_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [FoldingCash] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoldingCash].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FoldingCash] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FoldingCash] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FoldingCash] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FoldingCash] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FoldingCash] SET ARITHABORT OFF 
GO
ALTER DATABASE [FoldingCash] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FoldingCash] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FoldingCash] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FoldingCash] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FoldingCash] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FoldingCash] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FoldingCash] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FoldingCash] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FoldingCash] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FoldingCash] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FoldingCash] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FoldingCash] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FoldingCash] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FoldingCash] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FoldingCash] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FoldingCash] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FoldingCash] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FoldingCash] SET RECOVERY FULL 
GO
ALTER DATABASE [FoldingCash] SET  MULTI_USER 
GO
ALTER DATABASE [FoldingCash] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FoldingCash] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FoldingCash] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FoldingCash] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [FoldingCash] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'FoldingCash', N'ON'
GO
USE [FoldingCash]
GO
/****** Object:  Schema [FoldingCash]    Script Date: 6/29/2019 4:00:40 PM ******/
CREATE SCHEMA [FoldingCash]
GO
/****** Object:  Table [FoldingCash].[Downloads]    Script Date: 6/29/2019 4:00:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FoldingCash].[Downloads](
	[DownloadId] [int] IDENTITY(1,1) NOT NULL,
	[StatusId] [int] NOT NULL,
	[FileId] [int] NULL,
	[DownloadDateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Downloads] PRIMARY KEY CLUSTERED 
(
	[DownloadId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [FoldingCash].[Files]    Script Date: 6/29/2019 4:00:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FoldingCash].[Files](
	[FileId] [int] IDENTITY(1,1) NOT NULL,
	[FilePath] [nvarchar](250) NOT NULL,
	[FileName] [nvarchar](50) NOT NULL,
	[FileExtension] [nvarchar](5) NOT NULL,
 CONSTRAINT [PK_Files] PRIMARY KEY CLUSTERED 
(
	[FileId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [FoldingCash].[Rejections]    Script Date: 6/29/2019 4:00:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FoldingCash].[Rejections](
	[RejectionId] [int] IDENTITY(1,1) NOT NULL,
	[DownloadId] [int] NOT NULL,
	[Reason] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_Rejections] PRIMARY KEY CLUSTERED 
(
	[RejectionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [FoldingCash].[Statuses]    Script Date: 6/29/2019 4:00:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FoldingCash].[Statuses](
	[StatusId] [int] IDENTITY(1,1) NOT NULL,
	[Status] [nvarchar](50) NOT NULL,
	[StatusDescription] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Statuses] PRIMARY KEY CLUSTERED 
(
	[StatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [FoldingCash].[Downloads]  WITH CHECK ADD  CONSTRAINT [FK_Downloads_Files] FOREIGN KEY([FileId])
REFERENCES [FoldingCash].[Files] ([FileId])
GO
ALTER TABLE [FoldingCash].[Downloads] CHECK CONSTRAINT [FK_Downloads_Files]
GO
ALTER TABLE [FoldingCash].[Downloads]  WITH CHECK ADD  CONSTRAINT [FK_Downloads_Statuses] FOREIGN KEY([StatusId])
REFERENCES [FoldingCash].[Statuses] ([StatusId])
GO
ALTER TABLE [FoldingCash].[Downloads] CHECK CONSTRAINT [FK_Downloads_Statuses]
GO
ALTER TABLE [FoldingCash].[Rejections]  WITH CHECK ADD  CONSTRAINT [FK_Rejections_Downloads] FOREIGN KEY([DownloadId])
REFERENCES [FoldingCash].[Downloads] ([DownloadId])
GO
ALTER TABLE [FoldingCash].[Rejections] CHECK CONSTRAINT [FK_Rejections_Downloads]
GO
USE [master]
GO
ALTER DATABASE [FoldingCash] SET  READ_WRITE 
GO
